### PR TITLE
Use Inquiline 0.3.x

### PR DESCRIPTION
**Pull request by takebayashi**
This is needed for nestproject/NestTestSuite#7.

### CODE REVIEW

**Comment by takebayashi** [comment]
I think the version of Swift used in CI build is too old and should be upgraded

**Comment by kylef** [comment]
@takebayashi Can you rebase this PR on-top of master, that should hopefully fix the failure.

**Comment by takebayashi** [comment]
@kylef thanks. It has been fixed.

**Comment by kylef** [comment]
Thanks @takebayashi

**Pull request merged**
